deployment:
tasks:
- /bin/cp -a public_html/. /home/fahi3553/public_html/
- /bin/mkdir -p /home/fahi3553/app
- /bin/cp -a app/. /home/fahi3553/app/
- /bin/cp -a vendor/. /home/fahi3553/vendor/ || true
